# Generated by Django 5.2.17 on 2026-10-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected — not needed'), ('review', 'Review — changes needed')], max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='delivery_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='delivery_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected — not needed'), ('review', 'Review — changes needed')], default='pending', max_length=12),
        ),
    ]
