# Generated by Django 5.2.17 on 2026-10-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0002_comment_decision_property_delivery_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='version',
            name='review_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='upload_request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
