# Generated by Django 5.2.17 on 2026-10-04 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0003_comment_request_id_version_review_revision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='annotations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='proofs.comment'),
        ),
        migrations.AddField(
            model_name='photo',
            name='color_label',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='review_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='review_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='review_status',
            field=models.CharField(default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='version',
            name='clean_image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='version',
            name='clean_thumb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='GalleryDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('reason', models.CharField(blank=True, max_length=4000)),
                ('request_id', models.UUIDField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='proofs.property')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('config', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='proofs.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'photo'), name='favorite_user_photo')],
            },
        ),
    ]
