# Generated by Django 5.2.17 on 2026-10-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0004_comment_annotations_comment_parent_photo_color_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected — not needed'), ('review', 'Review — changes needed'), ('in_progress', 'In progress')], max_length=12),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected — not needed'), ('review', 'Review — changes needed'), ('in_progress', 'In progress')], default='pending', max_length=12),
        ),
    ]
