# Generated by Django 5.2.17 on 2026-10-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0005_alter_comment_decision_alter_version_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='annotations',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AlterField(
            model_name='photo',
            name='color_label',
            field=models.CharField(blank=True, db_default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='review_revision',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='review_settings',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='review_status',
            field=models.CharField(db_default='pending', default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='version',
            name='clean_image',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='version',
            name='clean_thumb',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
    ]
