# Generated by Django 5.2.17 on 2026-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0006_alter_comment_annotations_alter_photo_color_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='duration',
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='media_kind',
            field=models.CharField(db_default='image', default='image', max_length=8),
        ),
        migrations.AddField(
            model_name='version',
            name='processing',
            field=models.CharField(db_default='ready', default='ready', max_length=12),
        ),
        migrations.AddField(
            model_name='version',
            name='processing_error',
            field=models.CharField(blank=True, db_default='', default='', max_length=200),
        ),
        migrations.AddField(
            model_name='version',
            name='processing_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='source_file',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
    ]
