import { useRef, useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { api, write, message } from '@/api/client'
import type { Photo, Group } from '@/api/types'
import { Dialog, DialogContent, DialogTitle, DialogHeader, DialogDescription } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { ErrorNotice, SaveButton } from '@/components/common'
export function PhotoEditor({ photo, groups, mode, onClose }: { photo: Photo; groups: Group[]; mode: 'settings' | 'replacement' | null; onClose: () => void }) {
  const query = useQueryClient(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const key = useRef(crypto.randomUUID())
  return <Dialog open={Boolean(mode)} onOpenChange={open => { if (!open && !busy) onClose() }}><DialogContent><DialogHeader><DialogTitle>{mode === 'settings' ? 'Photo settings' : 'Upload new version'}</DialogTitle><DialogDescription>{mode === 'settings' ? 'Existing versions retain their embedded filenames.' : 'Earlier versions and feedback are preserved. The new version starts awaiting review.'}</DialogDescription></DialogHeader><form key={mode} className="form-stack" onSubmit={async e => { e.preventDefault(); setError(''); setBusy(true); const form = new FormData(e.currentTarget); try { if (mode === 'settings') await write(`photos/${photo.id}/`, { ...Object.fromEntries(form), hidden: form.has('hidden') }, 'PATCH'); else { form.set('request_id', key.current); await api(`photos/${photo.id}/versions/`, { method: 'POST', body: form }); key.current = crypto.randomUUID() } await query.invalidateQueries({ queryKey: ['photo', photo.id] }); await query.invalidateQueries({ queryKey: ['gallery', photo.property_id] }); await query.invalidateQueries({ queryKey: ['properties'] }); onClose() } catch (err) { setError(message(err)) } finally { setBusy(false) } }}>{error && <ErrorNotice error={error} />}{mode === 'settings' ? <><label>Photo name<Input name="name" defaultValue={photo.name} maxLength={140} required /></label><label>Room<select name="group" defaultValue={photo.group_id ?? ''}><option value="">Ungrouped</option>{groups.map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Order<Input name="position" type="number" min={0} defaultValue={photo.position} required /></label><label className="check-label"><input type="checkbox" name="hidden" defaultChecked={photo.hidden} />Hide from customer</label></> : <><label>Replacement photo<Input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required onChange={() => { key.current = crypto.randomUUID() }} /></label><label>What changed?<Input name="note" maxLength={500} placeholder="For example: corrected warmth" /></label><p className="caption">25 MB maximum, JPEG/PNG/WebP. Only watermarked review derivatives are stored.</p></>}<SaveButton busy={busy}>{mode === 'settings' ? 'Save changes' : 'Add version'}</SaveButton></form></DialogContent></Dialog>
}
