/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{id}/resolve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_comments_resolve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_customers_list"];
        put?: never;
        post: operations["v1_customers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_customers_partial_update"];
        trace?: never;
    };
    "/api/v1/feedback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_feedback_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_photos_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_photos_partial_update"];
        trace?: never;
    };
    "/api/v1/photos/{id}/favorite/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["v1_photos_favorite_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/{id}/label/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["v1_photos_label_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/{id}/versions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_photos_versions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_presets_list"];
        put?: never;
        post: operations["v1_presets_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_properties_list"];
        put?: never;
        post: operations["v1_properties_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_properties_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_properties_partial_update"];
        trace?: never;
    };
    "/api/v1/properties/{id}/decision/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_properties_decision_list"];
        put?: never;
        post: operations["v1_properties_decision_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_properties_groups_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{id}/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_properties_settings_partial_update"];
        trace?: never;
    };
    "/api/v1/properties/{id}/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_properties_upload_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_session_retrieve"];
        put?: never;
        post: operations["v1_session_create"];
        delete: operations["v1_session_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_versions_comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{id}/decision/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_versions_decision_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{id}/download/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_versions_download_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{id}/information/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_versions_information_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        Comment: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly version_id: string;
            readonly version_number: number;
            /** Format: uuid */
            readonly photo_id: string;
            readonly photo_name: string;
            readonly property_name: string;
            readonly author: components["schemas"]["User"];
            text: string;
            decision?: components["schemas"]["CommentDecisionEnum"] | components["schemas"]["BlankEnum"];
            resolved?: boolean;
            /** Format: date-time */
            readonly created: string;
            annotations?: unknown;
            /** Format: uuid */
            parent?: string | null;
        };
        /**
         * @description * `approved` - Approved
         *     * `rejected` - Rejected — not needed
         *     * `review` - Review — changes needed
         *     * `in_progress` - In progress
         * @enum {string}
         */
        CommentDecisionEnum: "approved" | "rejected" | "review" | "in_progress";
        CommentInput: {
            annotations?: unknown;
            /** Format: uuid */
            parent_id?: string | null;
            text: string;
            /** Format: uuid */
            request_id: string;
        };
        CustomerInput: {
            username: string;
            first_name?: string;
            password1: string;
            password2: string;
        };
        DecisionInput: {
            decision: components["schemas"]["DecisionInputDecisionEnum"];
            /** @default  */
            text: string;
            expected_revision: number;
            /** Format: uuid */
            request_id: string;
        };
        /**
         * @description * `approved` - approved
         *     * `rejected` - rejected
         *     * `review` - review
         *     * `in_progress` - in_progress
         * @enum {string}
         */
        DecisionInputDecisionEnum: "approved" | "rejected" | "review" | "in_progress";
        FavoriteContract: {
            favorite: boolean;
        };
        FeedbackResponse: {
            items: components["schemas"]["Comment"][];
            page: number;
            pages: number;
            count: number;
        };
        GalleryConfiguration: {
            view_only?: boolean;
            gallery_status?: boolean;
            asset_status?: boolean;
            favorites?: boolean;
            comments?: boolean;
            annotations?: boolean;
            color_labels?: boolean;
            download?: boolean;
            upload?: boolean;
            file_information?: boolean;
            workflow?: boolean;
            versioning?: boolean;
            watermark?: boolean;
            approved_downloads_only?: boolean;
            allowed_statuses?: string[];
            labels?: components["schemas"]["LabelDefinition"][];
        };
        GalleryDecisionContract: {
            id: string;
            status: string;
            reason: string;
            author: string;
            /** Format: date-time */
            created: string;
        };
        GalleryDecisionResult: {
            status: string;
            revision: number;
        };
        GalleryResponse: {
            property: components["schemas"]["Property"];
            groups: components["schemas"]["Group"][];
            photos: components["schemas"]["Photo"][];
        };
        Group: {
            readonly id: number;
            name: string;
            /** Format: int64 */
            position?: number;
        };
        InformationContract: {
            name: string;
            width: number;
            height: number;
            bytes: number;
            format: string;
            version: number;
            /** Format: date-time */
            created: string;
            kind: string;
        };
        LabelDefinition: {
            id: string;
            name: string;
            color: string;
            enabled: boolean;
        };
        LabelInput: {
            label: string;
        };
        LabelOutput: {
            color_label: string;
        };
        LoginInput: {
            username: string;
            password: string;
        };
        PasswordInput: {
            old_password: string;
            new_password1: string;
            new_password2: string;
        };
        PatchedCustomerUpdateInput: {
            is_active?: boolean;
            new_password1?: string;
            new_password2?: string;
        };
        PatchedGalleryConfiguration: {
            view_only?: boolean;
            gallery_status?: boolean;
            asset_status?: boolean;
            favorites?: boolean;
            comments?: boolean;
            annotations?: boolean;
            color_labels?: boolean;
            download?: boolean;
            upload?: boolean;
            file_information?: boolean;
            workflow?: boolean;
            versioning?: boolean;
            watermark?: boolean;
            approved_downloads_only?: boolean;
            allowed_statuses?: string[];
            labels?: components["schemas"]["LabelDefinition"][];
        };
        PatchedPhotoInput: {
            name?: string;
            group?: number | null;
            position?: number;
            hidden?: boolean;
        };
        PatchedPropertyInput: {
            name?: string;
            address?: string;
            customer?: number;
            archived?: boolean;
            delivery_url?: string;
            delivery_shared?: boolean;
        };
        Photo: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly property_id: string;
            name: string;
            readonly group_id: number | null;
            /** Format: int64 */
            position?: number;
            hidden?: boolean;
            readonly latest: components["schemas"]["Version"] | null;
            readonly versions: components["schemas"]["Version"][];
            readonly favorite: boolean;
            color_label?: string;
        };
        PhotoResponse: {
            photo: components["schemas"]["Photo"];
            comments: components["schemas"]["Comment"][];
        };
        PresetContract: {
            readonly id: string;
            name: string;
            config: components["schemas"]["GalleryConfiguration"];
            readonly standard: boolean;
        };
        Property: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            address?: string;
            readonly customer: components["schemas"]["User"];
            archived?: boolean;
            readonly delivery_url: string;
            delivery_shared?: boolean;
            readonly cover: components["schemas"]["Version"] | null;
            readonly photo_count: number;
            readonly reviewed_count: number;
            readonly review_settings: components["schemas"]["GalleryConfiguration"];
            review_status?: string;
            /** Format: int64 */
            review_revision?: number;
            readonly watermark_locked: boolean;
        };
        PropertyInput: {
            name: string;
            address?: string;
            customer: number;
            archived?: boolean;
            delivery_url?: string;
            delivery_shared?: boolean;
        };
        ReplacementInput: {
            /** Format: uuid */
            request_id: string;
            /** Format: uri */
            photo: string;
            note?: string;
        };
        ResolveInput: {
            resolved: boolean;
        };
        SessionResponse: {
            user: components["schemas"]["User"] | null;
            csrf: string;
            must_change_password: boolean;
            version: string;
        };
        /**
         * @description * `pending` - Awaiting review
         *     * `approved` - Approved
         *     * `rejected` - Rejected — not needed
         *     * `review` - Review — changes needed
         *     * `in_progress` - In progress
         * @enum {string}
         */
        StatusEnum: "pending" | "approved" | "rejected" | "review" | "in_progress";
        UploadInput: {
            group?: number | null;
            photos: string[];
        };
        User: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            /**
             * Staff status
             * @description Designates whether the user can log into this admin site.
             */
            is_staff?: boolean;
            /**
             * Active
             * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
             */
            is_active?: boolean;
        };
        Version: {
            /** Format: uuid */
            readonly id: string;
            /** Format: int64 */
            number: number;
            label: string;
            note?: string;
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created: string;
            /** Format: int64 */
            review_revision?: number;
            readonly image_url: string;
            readonly thumb_url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_comments_resolve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveInput"];
                "application/x-www-form-urlencoded": components["schemas"]["ResolveInput"];
                "multipart/form-data": components["schemas"]["ResolveInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    v1_customers_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    v1_customers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerInput"];
                "multipart/form-data": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    v1_customers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomerUpdateInput"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomerUpdateInput"];
                "multipart/form-data": components["schemas"]["PatchedCustomerUpdateInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    v1_feedback_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
        };
    };
    v1_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordInput"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordInput"];
                "multipart/form-data": components["schemas"]["PasswordInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    v1_photos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoResponse"];
                };
            };
        };
    };
    v1_photos_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPhotoInput"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPhotoInput"];
                "multipart/form-data": components["schemas"]["PatchedPhotoInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    v1_photos_favorite_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoriteContract"];
                "application/x-www-form-urlencoded": components["schemas"]["FavoriteContract"];
                "multipart/form-data": components["schemas"]["FavoriteContract"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteContract"];
                };
            };
        };
    };
    v1_photos_label_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelInput"];
                "application/x-www-form-urlencoded": components["schemas"]["LabelInput"];
                "multipart/form-data": components["schemas"]["LabelInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelOutput"];
                };
            };
        };
    };
    v1_photos_versions_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplacementInput"];
                "application/x-www-form-urlencoded": components["schemas"]["ReplacementInput"];
                "multipart/form-data": components["schemas"]["ReplacementInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    v1_presets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetContract"][];
                };
            };
        };
    };
    v1_presets_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetContract"];
                "application/x-www-form-urlencoded": components["schemas"]["PresetContract"];
                "multipart/form-data": components["schemas"]["PresetContract"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                    };
                };
            };
        };
    };
    v1_properties_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"][];
                };
            };
        };
    };
    v1_properties_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyInput"];
                "application/x-www-form-urlencoded": components["schemas"]["PropertyInput"];
                "multipart/form-data": components["schemas"]["PropertyInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyInput"];
                };
            };
        };
    };
    v1_properties_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryResponse"];
                };
            };
        };
    };
    v1_properties_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPropertyInput"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPropertyInput"];
                "multipart/form-data": components["schemas"]["PatchedPropertyInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    v1_properties_decision_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryDecisionContract"][];
                };
            };
        };
    };
    v1_properties_decision_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
                "application/x-www-form-urlencoded": components["schemas"]["DecisionInput"];
                "multipart/form-data": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryDecisionResult"];
                };
            };
        };
    };
    v1_properties_groups_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Group"];
                "application/x-www-form-urlencoded": components["schemas"]["Group"];
                "multipart/form-data": components["schemas"]["Group"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    v1_properties_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGalleryConfiguration"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGalleryConfiguration"];
                "multipart/form-data": components["schemas"]["PatchedGalleryConfiguration"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryConfiguration"];
                };
            };
        };
    };
    v1_properties_upload_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadInput"];
                "application/x-www-form-urlencoded": components["schemas"]["UploadInput"];
                "multipart/form-data": components["schemas"]["UploadInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    v1_session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    v1_session_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginInput"];
                "multipart/form-data": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    v1_session_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    v1_versions_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentInput"];
                "application/x-www-form-urlencoded": components["schemas"]["CommentInput"];
                "multipart/form-data": components["schemas"]["CommentInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    v1_versions_decision_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
                "application/x-www-form-urlencoded": components["schemas"]["DecisionInput"];
                "multipart/form-data": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    v1_versions_download_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
        };
    };
    v1_versions_information_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InformationContract"];
                };
            };
        };
    };
}
